<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.15" />
    <PackageReference Include="PersianDateTime" Version="1.1.5082.36395" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Domain\Dr.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Users\Commands\NewFolder\" />
  </ItemGroup>

</Project>
