// <auto-generated />
using System;
using Dr.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dr.Persistence.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20260621120506_dsjhfbvshdgbfvhdsuj")]
    partial class dsjhfbvshdgbfvhdsuj
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dr.Domain.Entities.Category.Category", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<long?>("ParentCategoryID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RemovedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Dr.Domain.Entities.Reserves.Appointments", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("AppoinmentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("CalenderID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("InsuranceID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisited")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemovedTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("ServiceID")
                        .HasColumnType("bigint");

                    b.Property<long>("TimeID")
                        .HasColumnType("bigint");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("lName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AppoinmentCode")
                        .IsUnique();

                    b.HasIndex("CalenderID");

                    b.HasIndex("InsuranceID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("TimeID");

                    b.HasIndex("TrackingCode")
                        .IsUnique();

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Dr.Domain.Entities.Reserves.CalenderD", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemovedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Calenders");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Date = new DateOnly(1405, 3, 31),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 2L,
                            Date = new DateOnly(1405, 4, 1),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 3L,
                            Date = new DateOnly(1405, 4, 2),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 4L,
                            Date = new DateOnly(1405, 4, 3),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 5L,
                            Date = new DateOnly(1405, 4, 4),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 6L,
                            Date = new DateOnly(1405, 4, 5),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 7L,
                            Date = new DateOnly(1405, 4, 6),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 8L,
                            Date = new DateOnly(1405, 4, 7),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 9L,
                            Date = new DateOnly(1405, 4, 8),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 10L,
                            Date = new DateOnly(1405, 4, 9),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 11L,
                            Date = new DateOnly(1405, 4, 10),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 12L,
                            Date = new DateOnly(1405, 4, 11),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 13L,
                            Date = new DateOnly(1405, 4, 12),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 14L,
                            Date = new DateOnly(1405, 4, 13),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 15L,
                            Date = new DateOnly(1405, 4, 14),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 16L,
                            Date = new DateOnly(1405, 4, 15),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 17L,
                            Date = new DateOnly(1405, 4, 16),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 18L,
                            Date = new DateOnly(1405, 4, 17),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 19L,
                            Date = new DateOnly(1405, 4, 18),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 20L,
                            Date = new DateOnly(1405, 4, 19),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 21L,
                            Date = new DateOnly(1405, 4, 20),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 22L,
                            Date = new DateOnly(1405, 4, 21),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 23L,
                            Date = new DateOnly(1405, 4, 22),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 24L,
                            Date = new DateOnly(1405, 4, 23),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 25L,
                            Date = new DateOnly(1405, 4, 24),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 26L,
                            Date = new DateOnly(1405, 4, 25),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 27L,
                            Date = new DateOnly(1405, 4, 26),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 28L,
                            Date = new DateOnly(1405, 4, 27),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 29L,
                            Date = new DateOnly(1405, 4, 28),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 30L,
                            Date = new DateOnly(1405, 4, 29),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 31L,
                            Date = new DateOnly(1405, 4, 30),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 32L,
                            Date = new DateOnly(1405, 5, 1),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 33L,
                            Date = new DateOnly(1405, 5, 2),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 34L,
                            Date = new DateOnly(1405, 5, 3),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 35L,
                            Date = new DateOnly(1405, 5, 4),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 36L,
                            Date = new DateOnly(1405, 5, 5),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 37L,
                            Date = new DateOnly(1405, 5, 6),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 38L,
                            Date = new DateOnly(1405, 5, 7),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 39L,
                            Date = new DateOnly(1405, 5, 8),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 40L,
                            Date = new DateOnly(1405, 5, 9),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 41L,
                            Date = new DateOnly(1405, 5, 10),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 42L,
                            Date = new DateOnly(1405, 5, 11),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 43L,
                            Date = new DateOnly(1405, 5, 12),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 44L,
                            Date = new DateOnly(1405, 5, 13),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 45L,
                            Date = new DateOnly(1405, 5, 14),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 46L,
                            Date = new DateOnly(1405, 5, 15),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 47L,
                            Date = new DateOnly(1405, 5, 16),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 48L,
                            Date = new DateOnly(1405, 5, 17),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 49L,
                            Date = new DateOnly(1405, 5, 18),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 50L,
                            Date = new DateOnly(1405, 5, 19),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 51L,
                            Date = new DateOnly(1405, 5, 20),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 52L,
                            Date = new DateOnly(1405, 5, 21),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 53L,
                            Date = new DateOnly(1405, 5, 22),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 54L,
                            Date = new DateOnly(1405, 5, 23),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 55L,
                            Date = new DateOnly(1405, 5, 24),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 56L,
                            Date = new DateOnly(1405, 5, 25),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 57L,
                            Date = new DateOnly(1405, 5, 26),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 58L,
                            Date = new DateOnly(1405, 5, 27),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 59L,
                            Date = new DateOnly(1405, 5, 28),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 60L,
                            Date = new DateOnly(1405, 5, 29),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 61L,
                            Date = new DateOnly(1405, 5, 30),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 62L,
                            Date = new DateOnly(1405, 5, 31),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 63L,
                            Date = new DateOnly(1405, 6, 1),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 64L,
                            Date = new DateOnly(1405, 6, 2),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 65L,
                            Date = new DateOnly(1405, 6, 3),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 66L,
                            Date = new DateOnly(1405, 6, 4),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 67L,
                            Date = new DateOnly(1405, 6, 5),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 68L,
                            Date = new DateOnly(1405, 6, 6),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 69L,
                            Date = new DateOnly(1405, 6, 7),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 70L,
                            Date = new DateOnly(1405, 6, 8),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 71L,
                            Date = new DateOnly(1405, 6, 9),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 72L,
                            Date = new DateOnly(1405, 6, 10),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 73L,
                            Date = new DateOnly(1405, 6, 11),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 74L,
                            Date = new DateOnly(1405, 6, 12),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 75L,
                            Date = new DateOnly(1405, 6, 13),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 76L,
                            Date = new DateOnly(1405, 6, 14),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 77L,
                            Date = new DateOnly(1405, 6, 15),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 78L,
                            Date = new DateOnly(1405, 6, 16),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 79L,
                            Date = new DateOnly(1405, 6, 17),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 80L,
                            Date = new DateOnly(1405, 6, 18),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 81L,
                            Date = new DateOnly(1405, 6, 19),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 82L,
                            Date = new DateOnly(1405, 6, 20),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 83L,
                            Date = new DateOnly(1405, 6, 21),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 84L,
                            Date = new DateOnly(1405, 6, 22),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 85L,
                            Date = new DateOnly(1405, 6, 23),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 86L,
                            Date = new DateOnly(1405, 6, 24),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 87L,
                            Date = new DateOnly(1405, 6, 25),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 88L,
                            Date = new DateOnly(1405, 6, 26),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 89L,
                            Date = new DateOnly(1405, 6, 27),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 90L,
                            Date = new DateOnly(1405, 6, 28),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 91L,
                            Date = new DateOnly(1405, 6, 29),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 92L,
                            Date = new DateOnly(1405, 6, 30),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 93L,
                            Date = new DateOnly(1405, 7, 1),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 94L,
                            Date = new DateOnly(1405, 7, 2),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 95L,
                            Date = new DateOnly(1405, 7, 3),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 96L,
                            Date = new DateOnly(1405, 7, 4),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 97L,
                            Date = new DateOnly(1405, 7, 5),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 98L,
                            Date = new DateOnly(1405, 7, 6),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 99L,
                            Date = new DateOnly(1405, 7, 7),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 100L,
                            Date = new DateOnly(1405, 7, 8),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 101L,
                            Date = new DateOnly(1405, 7, 9),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 102L,
                            Date = new DateOnly(1405, 7, 10),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 103L,
                            Date = new DateOnly(1405, 7, 11),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 104L,
                            Date = new DateOnly(1405, 7, 12),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 105L,
                            Date = new DateOnly(1405, 7, 13),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 106L,
                            Date = new DateOnly(1405, 7, 14),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 107L,
                            Date = new DateOnly(1405, 7, 15),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 108L,
                            Date = new DateOnly(1405, 7, 16),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 109L,
                            Date = new DateOnly(1405, 7, 17),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 110L,
                            Date = new DateOnly(1405, 7, 18),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 111L,
                            Date = new DateOnly(1405, 7, 19),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 112L,
                            Date = new DateOnly(1405, 7, 20),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 113L,
                            Date = new DateOnly(1405, 7, 21),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 114L,
                            Date = new DateOnly(1405, 7, 22),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 115L,
                            Date = new DateOnly(1405, 7, 23),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 116L,
                            Date = new DateOnly(1405, 7, 24),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 117L,
                            Date = new DateOnly(1405, 7, 25),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 118L,
                            Date = new DateOnly(1405, 7, 26),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = true,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 119L,
                            Date = new DateOnly(1405, 7, 27),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        },
                        new
                        {
                            ID = 120L,
                            Date = new DateOnly(1405, 7, 28),
                            InsertTime = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHoliday = false,
                            IsRemoved = false
                        });
                });

            modelBuilder.Entity("Dr.Domain.Entities.Reserves.Insurance", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemovedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Insurances");

                    b.HasData(
                        new
                        {
                            ID = 2L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "تامین اجتماعی"
                        },
                        new
                        {
                            ID = 3L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "خدمات درمانی"
                        },
                        new
                        {
                            ID = 4L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "ارتش جمهوری اسلامی ایران"
                        },
                        new
                        {
                            ID = 5L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "آزاد / بدون بیمه"
                        },
                        new
                        {
                            ID = 6L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "بانک ها"
                        },
                        new
                        {
                            ID = 7L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "اتباع محترم خارجی"
                        },
                        new
                        {
                            ID = 8L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "سایر بیمه ها"
                        });
                });

            modelBuilder.Entity("Dr.Domain.Entities.Reserves.Service", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RemovedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "ایمپلنت",
                            Price = 17800000
                        },
                        new
                        {
                            ID = 2L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "لمینیت",
                            Price = 17000000
                        },
                        new
                        {
                            ID = 3L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "ارتودنسی ثابت 2 فک",
                            Price = 95000000
                        },
                        new
                        {
                            ID = 4L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "کامپوزیت",
                            Price = 7000000
                        },
                        new
                        {
                            ID = 5L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "عصب کشی یک کانال",
                            Price = 4500000
                        },
                        new
                        {
                            ID = 6L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "ترمیم دندان",
                            Price = 1500000
                        },
                        new
                        {
                            ID = 7L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "روکش دندان",
                            Price = 2500000
                        });
                });

            modelBuilder.Entity("Dr.Domain.Entities.Reserves.Times", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Hour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Minute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemovedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Hour = "16",
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Minute = "00"
                        },
                        new
                        {
                            ID = 2L,
                            Hour = "16",
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Minute = "30"
                        },
                        new
                        {
                            ID = 3L,
                            Hour = "17",
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Minute = "00"
                        },
                        new
                        {
                            ID = 4L,
                            Hour = "17",
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Minute = "30"
                        },
                        new
                        {
                            ID = 5L,
                            Hour = "18",
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Minute = "00"
                        },
                        new
                        {
                            ID = 6L,
                            Hour = "18",
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Minute = "30"
                        });
                });

            modelBuilder.Entity("Dr.Domain.Entities.User.Role", b =>
                {
                    b.Property<long>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleID"));

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            RoleName = "Operator"
                        },
                        new
                        {
                            RoleID = 3L,
                            InsertTime = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("Dr.Domain.Entities.Users.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RePassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemovedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dr.Domain.Entities.Users.UserInRole", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RemovedTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserInRoles");
                });

            modelBuilder.Entity("Dr.Domain.Entities.Category.Category", b =>
                {
                    b.HasOne("Dr.Domain.Entities.Category.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryID");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Dr.Domain.Entities.Reserves.Appointments", b =>
                {
                    b.HasOne("Dr.Domain.Entities.Reserves.CalenderD", "Calender")
                        .WithMany()
                        .HasForeignKey("CalenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dr.Domain.Entities.Reserves.Insurance", "Insurance")
                        .WithMany()
                        .HasForeignKey("InsuranceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dr.Domain.Entities.Reserves.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dr.Domain.Entities.Reserves.Times", "Time")
                        .WithMany()
                        .HasForeignKey("TimeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calender");

                    b.Navigation("Insurance");

                    b.Navigation("Service");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Dr.Domain.Entities.Users.UserInRole", b =>
                {
                    b.HasOne("Dr.Domain.Entities.User.Role", "Role")
                        .WithMany("UserInRole")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dr.Domain.Entities.Users.User", "User")
                        .WithMany("UserInRole")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dr.Domain.Entities.Category.Category", b =>
                {
                    b.Navigation("ChildCategories");
                });

            modelBuilder.Entity("Dr.Domain.Entities.User.Role", b =>
                {
                    b.Navigation("UserInRole");
                });

            modelBuilder.Entity("Dr.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("UserInRole");
                });
#pragma warning restore 612, 618
        }
    }
}
